# Copyright 2021 Practically.io All rights reserved
#
#  Use of this source is governed by a BSD-style
#  licence that can be found in the LICENCE file or at
#  https://www.practically.io/copyright/

git:
  provider: github
  project: Practically/PsalmPluginYii2

hooks:
  commit-msg:
    - conventional-tools commitlint
  pre-push:
    - conventional-tools commitlint -l1
    - composer run-script test

  prepare-commit-msg:
    - |
        # Commitgen
        if [ -z "${2}" ]; then
            echo "$(conventional-tools commitgen)$(cat ${1})" > ${1};
        fi
  pre-commit:
    - composer run-script psalm
    - composer run-script cs:check-errors
