version: "3.7"

services:
  install-80:
    image: thecodingmachine/php:8.0-v4-cli
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/home/docker/.ssh
    command: composer install -o --no-scripts

  update-80:
    image: thecodingmachine/php:8.0-v4-cli
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/home/docker/.ssh
    command: composer update -o --no-scripts

  test-80:
    image: thecodingmachine/php:8.0-v4-cli
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/home/docker/.ssh
    command: composer test
